[project]
site_name = "Documentation for Apache Maven"
site_description = "Documentation site for Apache Maven."
site_author = "Maven Team"
copyright = "Apache, Apache Maven™, and the Apache Maven™ logo are either registered trademarks or trademarks of the Apache Software Foundation."
repo_name = "apache/maven"
repo_url = "https://github.com/apache/maven"
extra_css = ["assets/stylesheets/extra.css"]

nav = [
  { "Home" = "index.md" },
  { "Getting Started" = [
      { "Getting Started" = "get-started/index.md" },
      { "Install Maven" = "get-started/install-maven.md" },
      { "Quick Start" = "get-started/quick-start.md" },
      { "Build Lifecycle" = "get-started/build-lifecycle.md" },
      { "Migrate to Maven 4" = "get-started/migrate-maven-4.md" },
      { "Compatibility" = "get-started/compatibility.md" },
      { "License" = "get-started/license.md" }
  ]},
  { "User Guide" = [
      { "Overview" = "usage/index.md" }
  ]},
  { "Configuration" = [
      { "Overview" = "setup/index.md" }
  ]},
  { "Plugins" = [
      { "Overview" = "authoring/index.md" }
  ]},
  { "Community" = [
      { "Overview" = "community/index.md" }
  ]}
]

[project.theme]
language = "en"
logo = "assets/maven.svg"
features = [
  "announce.dismiss",
  "navigation.footer",
  "navigation.indexes",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.top",
  "search.highlight"
]

[[project.theme.palette]]
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "orange"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

